kind: ConfigMap
apiVersion: v1
metadata:
  name: mutischeduler-config
  namespace: wolf
data:
  config.json: |-
    {
        "http_api_port":9009,
        "cluster_mode":true,
        "node_mcluster":{
            "mcluster1":{
                "host_addr":"192.168.100.156:8966"
            }
        }
    }
