apiVersion: apps/v1
kind: Deployment
metadata:
  name: isd
  namespace: wolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: isd
  template:
    metadata:
      labels:
        name: isd
    spec:
      containers:
      - name: isd
        image: dockerhub.deepglint.com/wolf/isd:0.9.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 7070
        command: ["./isdst"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        volumeMounts:
        - name: isd-config
          mountPath: /isd/tmp
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: isd-config
          configMap:
            name: isd-config
        - name: localtime
          hostPath:
            path: /etc/localtime
