apiVersion: v1
kind: ConfigMap
metadata:
  name: isd-config
  namespace: {{.Values.namespace}}
data:
  isdconfig.txt: |
    {
        "StreamToolsConfig":{
            "Port":"7070"
        },
        "ImageSaveServiceConfig":{
            "IsOpen":true,
            "ConfigType":1,
            "ConfigInfo":{
                "Host":"arcee-capture-service.wolf.svc.cluster.local:8502",
                "TimeoutSecond":3,
                "ConnectNumber":5
            }
        },
        "MatrixServiceConfig":{
            "IsOpen":true,
            "Addr":"http://ingress-nginx.ingress-nginx.svc.cluster.local:80/vse/face/rec/image",
            "StructuredAddr":"http://ingress-nginx.ingress-nginx.svc.cluster.local:80/vse/vehicle/rec/image",
            "ConnectNumber":10,
            "TimeoutSecond":5,
            "TryTimes":3
        },
        "SingleObjectNodeConfig":{
            "MaxThread":100,
            "Context":{
                "SessionId":"single_face",
                "Functions":[
                    200
                ],
                "Type":2,
                "Params":{
                    "detect_mode":"1"
                }
            },
            "StructuredContext":{
                "SessionId":"single_object",
                "Functions":[
                    100
                ],
                "Type":2,
                "Params":{
                    "detect_mode":"1"
                }
            }
        },
        "ImageStorageNodeConfig":{
            "ImageSaveMaxThread":100
        },
        "KafkaInputNodeConfig":{
            "Brokers":[
                "{{.Values.KAFKA_ADDRESS}}"
            ],
            "Topics":[
                "face-importer"
            ],
            "Group":"g1",
            "MaxFetchBytes":"104857600",
            "SendMessageTimeout":5
        },
        "KafkaOutputNodeConfig":{
            "KafkaAddress":[
                "{{.Values.KAFKA_ADDRESS}}"
            ],
            "KafkaTopic":"index-vehicle2",
            "MaxMessageBytes":"104857600",
            "KafkaSentMaxThread":100,
            "IsCompression":false
        }
    }
