apiVersion: v1
kind: Service
metadata:
  name: isd-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    name: isd
  ports:
  - name: http
    port: 7070
    targetPort: 7070
    nodePort: 30070
