apiVersion: v1
kind: Service
metadata:
  name: bultgang-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: bultgang
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    nodePort: 18082
