apiVersion: apps/v1
kind: Deployment
metadata:
  name: bultgang
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bultgang
  template:
    metadata:
      labels:
        name: bultgang
    spec:
      containers:
      - name: bultgang
        image: dockerhub.deepglint.com/deepface/{{.Values.bultgang.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8082
        command: ["./run"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        env:
        - name: BASE_KAFKA_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_KAFKA_ADDRESS
        - name: BASE_PG_DEEPFACE_V5_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_PG_DEEPFACE_V5_ADDRESS
        - name: APPLICATION_LOKI_HOST
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: APPLICATION_LOKI_HOST
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
