apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv-0
  namespace: pgsql
  labels:
    app: pgsql-pv-0
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /data/bigtoe/postgres/pv0
