apiVersion: v1
kind: Namespace
metadata:
  name: pgsql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pgsql-0
  namespace: pgsql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  storageClassName: slow
  selector:
    matchLabels:
      app: "pgsql-pv-0"
