apiVersion: v1
kind: ConfigMap
metadata:
  name: archimedes-config
  namespace: {{.Values.namespace}}
data:
  config.json: |
    {
        "Debug": true,
        "HttpConfig": {
            "Addr": "0.0.0.0:6666"
        },
        "DBServiceConfig": {
            "IsOpen": true,
            "ConfigType": 1,
            "ConfigInfo": {
                "DBType": "postgres",
                "Host": "postgres-service.wolf.svc.cluster.local",
                "Port": 5432,
                "UserName": "postgres",
                "PassWord": "Zstvgcs@9102",
                "DBName": "statistics",
                "MaxOpenConnsPerClient": 40,
                "MaxIdleConnsPerClient": 40,
                "MaxLifeTimeSeconds": 60,
                "IsShowSQL": true
            }
        },
        "RedisServiceConfig": {
            "Addr": "redis-service.wolf.svc.cluster.local:6378",
            "Password": "deepglint@2013",
            "DB": 3,
            "Comment": "config: archimedes.redis.db==ullr.redis.db, archimedes.pg.statistics==ullr.pg.statistics",
            "SpecialVehicleCountKey": "vehicle-special-count"
        },
        "CommonCaptureCountServiceConfig": {
            "MaxDbThread": 200,
            "MaxRedisThread": 20,
            "NumInsideSQL": 100,
            "HistoryExpireMillSeconds": 720000,
            "NowHourExpireMillSeconds": 5000
        },
        "CommonEventCountServiceConfig": {
            "MaxDbThread": 200,
            "MaxRedisThread": 20,
            "NumInsideSQL": 100,
            "HistoryExpireMillSeconds": 720000,
            "NowHourExpireMillSeconds": 5000
        },
        "CacheUtilConfig": {
            "ExpireMillSeconds": 2000
        },
        "DbConfig": {
            "VehicleAttrHour": {
                "MaxDbThread": 30,
                "TsStepMillSecond": 7200000
            },
            "VehicleAttrDay": {
                "MaxDbThread": 30,
                "TsStepMillSecond": 86400000
            },
            "FaceAttrHour": {
                "MaxDbThread": 30,
                "TsStepMillSecond": 7200000
            },
            "FaceAttrDay": {
                "MaxDbThread": 30,
                "TsStepMillSecond": 86400000
            }
        }
    }
