apiVersion: v1
kind: Service
metadata:
  name: archimedes-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    name: archimedes
  ports:
  - name: http
    port: 6666
    targetPort: 6666
    nodePort: 31066
