apiVersion: apps/v1
kind: Deployment
metadata:
  name: archimedes
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: archimedes
  template:
    metadata:
      labels:
        name: archimedes
    spec:
      containers:
      - name: archimedes
        image: dockerhub.deepglint.com/deepface/{{.Values.archimedes.imageTag}}
        imagePullPolicy: IfNotPresent
        env:
        - name: BASE_PG_STATISTICS_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_PG_STATISTICS_ADDRESS
        - name: BASE_ARCHIMEDES_REDIS_CACHE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_ARCHIMEDES_REDIS_CACHE_ADDRESS
        ports:
        - name: http
          containerPort: 6666
        command: ["./run"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=4"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
