apiVersion: apps/v1
kind: Deployment
metadata:
  name: croatia
  namespace: wolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: croatia
  template:
    metadata:
      labels:
        name: croatia
    spec:
      containers:
      - name: croatia
        image: dockerhub.deepglint.com/wolf/croatia:2.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 1314
        command: ["./croatia"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        volumeMounts:
        - name: croatia-config
          mountPath: /croatia/config
        - name: croatia-upload
          mountPath: /platformData/loki/upload
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: croatia-config
          configMap:
            name: croatia-config
        - name: croatia-upload
          hostPath:
            path: /platformData/loki/upload
        - name: localtime
          hostPath:
            path: /etc/localtime
