apiVersion: v1
kind: Service
metadata:
  name: croatia-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: croatia 
  ports:
  - name: http
    port: 1314
    targetPort: 1314
    nodePort: 31314
