apiVersion: apps/v1
kind: Deployment
metadata:
  name: croatia
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: croatia
  template:
    metadata:
      labels:
        name: croatia
    spec:
      containers:
      - name: croatia
        image: dockerhub.deepglint.com/deepface/{{.Values.croatia.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 1314
        command: ["./run"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        env:
        - name: BASE_PG_DEEPFACE_V5_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_PG_DEEPFACE_V5_ADDRESS
        - name: BASE_VSE_ALL_HOST
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_VSE_ALL_HOST
        - name: BASE_FSE_HOST
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_FSE_HOST
        - name: BASE_PIC_REGISTER_HOST
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_PIC_REGISTER_HOST
        - name: APPLICATION_LOKI_HOST
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: APPLICATION_LOKI_HOST
        volumeMounts:
        - name: croatia-upload
          mountPath: /platformData/loki/upload
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: croatia-upload
          hostPath:
            path: /platformData/loki/upload
        - name: localtime
          hostPath:
            path: /etc/localtime
