apiVersion: apps/v1
kind: Deployment
metadata:
  name: saxvehicle
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: saxvehicle
  template:
    metadata:
      labels:
        name: saxvehicle
    spec:
      containers:
      - name: saxvehicle
        image: dockerhub.deepglint.com/wolf/sax_vehicle:{{.Values.sax_vehicle.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8084
#        command: ["./sv_start.sh"]
        volumeMounts:
        - name: saxvehicle-config
          mountPath: /saxvehicle/config
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: saxvehicle-config
          configMap:
            name: saxvehicle-config
        - name: localtime
          hostPath:
            path: /etc/localtime
