apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: wolf
  labels:
     app: pgsql
spec:
     replicas: 1
     selector:
       matchLabels:
         app: pgsql
     template:
       metadata:
         labels:
           app: pgsql
       spec:
         containers:
         - name: pgsql
           image: postgres:11.4
           env:
           - name: POSTGRES_USER
             value: postgres
           - name: POSTGRES_PASSWORD
             value: Zstvgcs@9102
           imagePullPolicy: IfNotPresent
           args: ["postgres", "-c", "config_file=/postgresql/postgresql.conf"]
           ports:
           - containerPort: 5432
           volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgredb
           - mountPath: /etc/localtime
             name: localtime
           - mountPath: /postgresql/postgresql.conf
             name: pgsql-config
             subPath: postgresql.conf
           #- mountPath: /var/lib/postgresql/data
           #  name: pgsql-connect
           #  subPath: pg_hba.conf
         volumes:
            - name: postgredb
              hostPath:
                path: /platformData/postgresql2
              #persistentVolumeClaim:
              #  claimName: data-pgsql-0
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: pgsql-config
              configMap:
                name: pgsql-config
           # - name: pgsql-connect
           #   configMap:
           #     name: pgsql-config
       #  nodeSelector:
       #    bindNode: k8s-master
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    app: pgsql
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30543
