apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: {{.Values.namespace}}
  labels:
     app: pgsql
spec:
     replicas: 1
     selector:
       matchLabels:
         app: pgsql
     template:
       metadata:
         labels:
           app: pgsql
       spec:
         containers:
         - name: pgsql
           image: dockerhub.deepglint.com/wolf/postgres:11.4
           env:
           - name: POSTGRES_USER
             value: postgres
           - name: POSTGRES_PASSWORD
             value: Zstvgcs@9102
           imagePullPolicy: IfNotPresent
           args: ["postgres", "-c", "config_file=/postgresql/postgresql.conf"]
           ports:
           - containerPort: 5432
           volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgredb
           - mountPath: /etc/localtime
             name: localtime
           - mountPath: /postgresql/postgresql.conf
             name: pgsql-config
             subPath: postgresql.conf
         volumes:
            - name: postgredb
              hostPath:
                path: /platformData/postgresql2
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: pgsql-config
              configMap:
                name: pgsql-config
         nodeSelector:
           bindNode: k8s-master
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    app: pgsql
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30543
