apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{.Values.namespace}}
  labels:
     app: redis
spec:
     replicas: 1
     selector:
       matchLabels:
         app: redis
     template:
       metadata:
         labels:
           app: redis
       spec: 
         nodeSelector:
           bindNode: k8s-master
         containers:
         - name: cache
           image: redis:{{.Values.redis.imageTag}}
           command: 
           - "redis-server"
           args: 
           - "/redis-cache-config/redis.conf"
           env:
           - name: MASTER
             value: "true"
           imagePullPolicy: IfNotPresent
           ports:
           - containerPort: 6379
           volumeMounts:
           - name: cache-data
             mountPath: /redis-cache-data
           - name: cache-config
             mountPath: /redis-cache-config
           - name: localtime
             mountPath: /etc/localtime
         - name: persistence 
           image: redis:{{.Values.redis.imageTag}}
           command: 
           - "redis-server"
           args: 
           - "/redis-persistence-config/redis.conf"
           env:
           - name: MASTER
             value: "true"
           imagePullPolicy: IfNotPresent
           ports:
           - containerPort: 6380
           volumeMounts:
           - name: persistence-data
             mountPath: /redis-persistence-data
           - name: persistence-config
             mountPath: /redis-persistence-config
           - name: localtime
             mountPath: /etc/localtime
         volumes:
            - name: cache-data
              emptyDir: {}
            - name: cache-config
              configMap:
                name: cache-configmap
            - name: persistence-data
              hostPath:
                path: /platformData/redis
            - name: persistence-config
              configMap:
                name: persistence-configmap
            - name: localtime
              hostPath:
                path: /etc/localtime
         nodeSelector:
           bindNode: k8s-master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: cache
    port: 6379
    targetPort: 6379
  - name: persistence
    port: 6380
    targetPort: 6380
