apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-0
  namespace: redis
  labels:
    app: redis-pv-0
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /data/bigtoe/redis/pv0