kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-0
  namespace: redis
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow
  selector:
    matchLabels:
      app: "redis-pv-0"
