apiVersion: apps/v1
kind: Deployment
metadata:
  name: jormougand
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jormougand
  template:
    metadata:
      labels:
        name: jormougand
    spec:
      containers:
      - name: jormougand
        image: dockerhub.deepglint.com/deepface/jormougand:{{.Values.jormougand.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: jormougand-config
          mountPath: /etc/nginx/conf.d
        - name: platformdata-dir
          mountPath: /platformData
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: jormougand-config
          configMap:
            name: jormougand-nginx-config
        - name: platformdata-dir
          hostPath:
            path: /platformData
        - name: localtime
          hostPath:
            path: /etc/localtime
