apiVersion: v1
kind: Service
metadata:
  name: jormougand-service
  namespace: wolf
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    name: jormougand
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 80
