apiVersion: v1
kind: Service
metadata:
  name: jormougand-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: jormougand
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30880
