apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: deepdata-warwolf
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
     path: /data/bigtoe/upload-videos
     server: 192.168.5.78
     readOnly: false
