apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-config
  namespace: {{.Values.namespace}}
data:
  config.json: |
    {
        "ApiHttpConfig":{
            "Host":"0.0.0.0:8083"
        },
        "RepositoriesConfig":{
            "TriggerDomain":{
                "ConfigType":1,
                "ConfigInfo":{
                    "ClientNum":1,
                    "Host":"postgres-service.wolf.svc.cluster.local",
                    "Port":5432,
                    "UserName":"postgres",
                    "PassWord":"Zstvgcs@9102",
                    "DBName":"deepface_v5",
                    "MaxOpenConnsPerClient":20,
                    "MaxIdleConnsPerClient":20,
                    "MaxLifeTimeSeconds":60,
                    "ShowSQL":false
                }
            }
        },
        "TriggerConfig":{
            "TimeIntervalMillSecond":2000,
            "KeyMap":{
                "org_trigger":[
                    "OrgChange"
                ],
                "task_trigger":[
                    "TaskChange"
                ],
                "sensor_trigger":[
                    "SensorChange",
                    "UserChange"
                ],
                "monitor_trigger":[
                    "MonitorChange",
                    "MonitorRepoRelationChange",
                    "MonitorSensorRelationChange",
                    "MonitorExtendChange"
                ]
            }
        },
        "VisibilityConfig":{
            "Sensor":[
                "SensorChange"
            ]
        },
        "TaskConfig":{
            "0":{
                "Description":"测试用任务",
                "TimeIntervalMillSecond":1000
            },
            "1":{
                "Description":"累计抓拍统计",
                "TimeIntervalMillSecond":2000,
                "ShowLog":false
            },
            "2":{
                "Description":"累计报警统计",
                "TimeIntervalMillSecond":2000,
                "ShowLog":false
            },
            "3":{
                "Description":"今日档案统计",
                "TimeIntervalMillSecond":2000,
                "ShowLog":false
            }
        },
        "ClientConfig":{
            "QueueCapacity":10,
            "TimeoutMillSecond":3000
        },
        "LogConfig":{
            "HttpRequest":false
        },
        "DependenciesConfig":{
            "Archimedes":{
                "Address":"http://archimedes-service.wolf.svc.cluster.local:6666/archimedes/v1",
                "TimeoutSecond":60
            },
            "Flora":{
                "Address":"http://flora-service.wolf.svc.cluster.local:4000/api/v1",
                "TimeoutSecond":60
            },
            "Loki":{
                "Address":"http://loki-service.wolf.svc.cluster.local:3000/",
                "TimeoutSecond":60
            }
        }
    }
