apiVersion: v1
kind: Service
metadata:
  name: flora-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: flora
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    nodePort: 4000
