apiVersion: apps/v1
kind: Deployment
metadata:
  name: flora
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flora
  template:
    metadata:
      labels:
        name: flora
    spec:
      containers:
      - name: flora
        image: dockerhub.deepglint.com/deepface/{{.Values.flora.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 4000
        command: ["./flora"]
        args:
        - "-level=0"
        env:
        - name: ENVIRONMENT
          value: production
        - name: BASE_PG_DEEPFACE_V5_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_PG_DEEPFACE_V5_ADDRESS
        - name: BASE_REDIS_CACHE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_REDIS_CACHE_ADDRESS
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
