apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: wolf
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      kafka {
        id => "logstash_id"
        bootstrap_servers => ["bootstrap.kafka.svc.cluster.local:9092"]
        topics => ["user_operation_log"]     # kafka.topic
        # group_id => "logstash"             # default logstash
        # client_id => "logstash"            # default logstash
        consumer_threads => 5
        auto_offset_reset => "latest"      # earliest, latest
        decorate_events => true            # metadata
        enable_auto_commit => true         # when the process fails: offset_reset
        codec => "json"
      }
    }
    
    filter {
      json {
        source => ""
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elk-service.wolf.svc.cluster.local:9200"]
        index => "user_operation_log"
        # user => "elastic"
        # password => "changeme"
      }
      stdout {
        codec => "json"
      }
    }
