apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elastic
  template:
    metadata:
      labels:
        name: elastic
    spec:
      containers:
      - name: elastic
        image: dockerhub.deepglint.com/deepface/{{.Values.elastic.imageTag}}
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: single-node
        ports:
        - name: http
          containerPort: 9200
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: elk-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elk-data
          hostPath:
            path: /platformData/elk/elasticsearch/data
        - name: localtime
          hostPath:
            path: /etc/localtime
