apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfspv
  namespace: deepdata-warwolf
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
     path: /data/seaweedfs/volume
