apiVersion: v1
kind: Service
metadata:
  name: master-seaweedfs-service
  namespace: deepdata-warwolf
spec:
  type: NodePort
  selector:
    name: master-seaweedfs-service
  ports:
  - name: master-http
    port: 9333
    targetPort: 9333
    nodePort: 30333
  - name: master-grpc
    port: 19333
    targetPort: 19333

---

apiVersion: v1
kind: Service
metadata:
  name: volume-hostpath-seaweedfs-service
  namespace: deepdata-warwolf
spec:
  type: NodePort
  selector:
    name: volume-hostpath-seaweedfs-service
  ports:
  - name: volume-http
    port: 9300
    targetPort: 9300
    nodePort: 30300
  - name: volume-grpc
    port: 19300
    targetPort: 19300

---

apiVersion: v1
kind: Service
metadata:
  name: volume-nfs-seaweedfs-service
  namespace: deepdata-warwolf
spec:
  type: NodePort
  selector:
    name: volume-nfs-seaweedfs-service
  ports:
  - name: volume-http
    port: 9301
    targetPort: 9301
    nodePort: 30301
  - name: volume-grpc
    port: 19301
    targetPort: 19301
