apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: loki
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 3000
