apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: athena
  template:
    metadata:
      labels:
        name: athena
    spec:
      containers:
      - name: athena
        image: dockerhub.deepglint.com/wolf/athena:{{.Values.athena.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 2013
        command: ["./athena"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        volumeMounts:
        - name: athena-run-config
          mountPath: /athena/athenadir/config
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: athena-run-config
          configMap:
            name: athena-config
        - name: localtime
          hostPath:
            path: /etc/localtime
