apiVersion: v1
kind: Service
metadata:
  name: athena-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    name: athena
  ports:
  - name: http
    port: 2013
    targetPort: 2013
    nodePort: 32013
