apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: athena
  template:
    metadata:
      labels:
        name: athena
    spec:
      containers:
      - name: athena
        image: dockerhub.deepglint.com/deepface/{{.Values.athena.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 2013
        command: ["./run"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        env:
        - name: BASE_PG_DEEPFACE_V5_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_PG_DEEPFACE_V5_ADDRESS
        - name: BASE_FSE_HOST
          valueFrom:
            configMapKeyRef:
              name: basenv
              key: BASE_FSE_HOST
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
