apiVersion: v1
kind: ConfigMap
metadata:
  name: athena-config
  namespace: wolf
data:
  config.json: |
    {
        "AthenaBaseConfig":{
            "ListenAddr":"0.0.0.0:2013",
            "MaxTaskNum":500,
            "DictAddr":{
                "BrandAddr":"./athenadir/dict/INDEX_BRAND.json",
                "FaceAddr":"./athenadir/dict/INDEX_FACE.json",
                "LicensePlateAddr":"./athenadir/dict/INDEX_LICENSE_PLATE.json",
                "MotorAddr":"./athenadir/dict/INDEX_MOTOR.json",
                "NonMotorAddr":"./athenadir/dict/INDEX_NON_MOTOR.json",
                "PedestrianAddr":"./athenadir/dict/INDEX_PEDESTRIAN.json"
            },
            "AthenaTmpDir":"/platformData/athenadir/tmp/",
            "StatusTmpDir":"/platformData/athenadir/tmp/status/",
            "MaxQueueLength":30,
            "MaxRunningTasks":20
        },
        "DBServiceConfig":{
            "IsOpen":false,
            "ConfigType":"xorm",
            "ConfigInfo":{
                "DBType":"postgres",
                "Host":"postgres-service.wolf.svc.cluster.local",
                "Port":5432,
                "UserName":"postgres",
                "PassWord":"Zstvgcs@9102",
                "DBName":"deepface_v5",
                "MaxOpenConnsPerClient":2,
                "MaxIdleConnsPerClient":2,
                "MaxLifeTimeSeconds":60,
                "IsShowSQL":false
            }
        },
        "RankerConfig":{
            "WarnRankerAddr":"http://fseapi-service.fse.svc.cluster.local:8000/x-api/v1",
            "WarnRankerConnectNumber":10,
            "TimeoutSecond":5,
            "TryTimes":3
        }
    }
  tasks_config.json: |
    {
        "ExportTaskConfig":{
            "MaxGoroutinesToLoadPic":10,
            "LoadPicTimeout":20,
            "MaxRecordsCountPerExcel":2000,
            "MaxTotalRecords":10000,
            "ExportPath":"/platformData/athenadir/tmp/exporttask/result",
            "TempPath":"/platformData/athenadir/tmp/exporttask"
        },
        "ExportSql2ExcelTaskConfig":{
            "PageSize":2000,
            "MaxGoroutinesToLoadPic":10,
            "MaxRecordCountPerExcel":2000,
            "MaxTotalRecords":10000,
            "ExportPath":"/platformData/athenadir/tmp/exportsqltoexceltask/result",
            "TempPath":"/platformData/athenadir/tmp/exportsqltoexceltask"
        },
        "ExportSql2ExcelWithParamBeyondDbTaskConfig":{
            "PageSize":2000,
            "MaxGoroutinesToLoadPic":10,
            "MaxRecordCountPerExcel":2000,
            "MaxTotalRecords":10000,
            "ExportPath":"/platformData/athenadir/tmp/exportsqltoexcelwithparambeyonddbtask/result",
            "TempPath":"/platformData/athenadir/tmp/exportsqltoexcelwithparambeyonddbtask"
        },
        "PersonAreaCollisionTaskConfig":{
    
        },
        "PersonFrequencyAnalysisTaskConfig":{
            "TsStep":21600000
        },
        "PersonRepoCollisionTaskConfig":{
            "Limit":100,
            "RankerGetFeatureMaxThread":10
        },
        "PersonTrailMatchTaskConfig":{
            "TsStep":21600000
        },
        "PlatformSyncGbTaskConfig":{
            "Uri":"http://{{.Values.HOSTIP}}:8000/dgsip/catalog",
            "LastUpdateKey":"helloplatformsynclastupdatekey",
            "Timeout":600
        },
        "PlatformSyncPVGTaskConfig":{
            "Uri":"http://{{.Values.HOSTIP}}:7457/vse/catalog",
            "LastUpdateKey":"pvghelloplatformsynclastupdatekey",
            "Timeout":600
        },
        "VehicleAreaCollisionTaskConfig":{
    
        },
        "VehicleDayInNightOutTaskConfig":{
            "TsStep":3600000,
            "Comment":"default: 3600000 = 1h"
        },
        "VehicleFakePlateTaskConfig":{
            "TsStep":21600000,
            "MaxSpeed":132,
            "PositionThreshold":50,
            "DistanceThreshold":2000
        },
        "VehicleFirstAppearanceTaskConfig":{
            "TsStep":21600000
        },
        "VehicleFrequencyAnalysisTaskConfig":{
            "TsStep":21600000
        },
        "VehicleHiddenTaskConfig":{
            "TsStep":21600000,
            "DaysBeforeEvent":4,
            "DaysAfterEvent":3,
            "MinAppearanceTimesBeforeEvent":2,
            "MaxHiddenCoefficient":0.3
        },
        "VehicleTrailMatchTaskConfig":{
            "TsStep":21600000
        }
    }
