apiVersion: v1
kind: Service
metadata:
  name: capture-seaweedfs-service-master
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: capture-seaweedfs-master
  ports:
  - name: http
    port: 9333
    targetPort: 9333
    nodePort: 9333
  - name: grpc
    port: 19333
    targetPort: 19333
    nodePort: 19333

---

apiVersion: v1
kind: Service
metadata:
  name: capture-seaweedfs-service-volume00
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: capture-seaweedfs-volume00
  ports:
  - name: http
    port: 9300
    targetPort: 9300
    nodePort: 9300
  - name: grpc
    port: 19300
    targetPort: 19300
    nodePort: 19300

---

apiVersion: v1
kind: Service
metadata:
  name: register-seaweedfs-service-master
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: register-seaweedfs-master
  ports:
  - name: http
    port: 5333
    targetPort: 5333
    nodePort: 5333
  - name: grpc
    port: 15333
    targetPort: 15333
    nodePort: 15333

---

apiVersion: v1
kind: Service
metadata:
  name: register-seaweedfs-service-volume00
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: register-seaweedfs-volume00
  ports:
  - name: http
    port: 5300
    targetPort: 5300
    nodePort: 5300
  - name: grpc
    port: 15300
    targetPort: 15300
    nodePort: 15300

