apiVersion: v1
kind: ConfigMap
metadata:
  name: eventpoxy-config
  namespace: {{.Values.namespace}}
data:
  config.json: |
    {
      "Sevice": {
        "LogLevel": "info",
        "EventsKeepTime": 30,
        "Port":":1919"
      },
      "WsEventService":{
        "WsAdress":"k2s-service.wolf.svc.cluster.local:8082",
        "UserId":"0000",
        "Types":[16]
      }
    }
