apiVersion: v1
kind: ConfigMap
metadata:
  name: eventpoxy-config
  namespace: wolf
data:
  config.json: |
    {
      "Sevice": {
        "QueryTimeInterval": 3,
        "LogLevel": "error",
        "EventsKeepTime": 30,
        "Port": ":1919"
      },
      "Loki": {
        "LokiApiAddr":"http://loki-service.wolf.svc.cluster.local:3000/api/face/events"
      },
      "RequestInfo": {
        "TimeSpan": 30,
        "Confidence": 0.8,
        "Limit": 50
      }
    }
