apiVersion: v1
kind: Service
metadata:
  name: eventpoxy-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    name: eventpoxy
  ports:
  - name: http
    port: 1919
    targetPort: 1919
    nodePort: 31019
