apiVersion: v1
kind: Service
metadata:
  name: odin-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    name: odin
  ports:
  - name: http
    port: 7071
    targetPort: 7071
    nodePort: 30071
