apiVersion: apps/v1
kind: Deployment
metadata:
  name: themis
  namespace: wolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: themis
  template:
    metadata:
      labels:
        name: themis
    spec:
      containers:
      - name: themis
        image: dockerhub.deepglint.com/wolf/themis:0.8.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 7777
        command: ["./themis"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=4"
        volumeMounts:
        - name: themis-config
          mountPath: /themis/config.json
          subPath: config.json
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: themis-config
          configMap:
            name: themis-config
        - name: localtime
          hostPath:
            path: /etc/localtime
