apiVersion: v1
kind: Service
metadata:
  name: themis-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    name: themis
  ports:
  - name: http
    port: 7777
    targetPort: 7777
    nodePort: 7777
