apiVersion: apps/v1
kind: Deployment
metadata:
  name: k2s
  namespace: wolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k2s
  template:
    metadata:
      labels:
        name: k2s
    spec:
      containers:
      - name: k2s
        image: dockerhub.deepglint.com/wolf/k2s:0.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8082
        command: ["./k2s"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-f=/k2s/config/config.json"
        - "-v=4"
        volumeMounts:
        - name: k2s-config
          mountPath: /k2s/config
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: k2s-config
          configMap:
            name: k2s-config
        - name: localtime
          hostPath:
            path: /etc/localtime
